name: Build Codegen

on:
  pull_request:
  push:
    branches:
    - 'prebuilt-codegen'

jobs:
  # https://stackoverflow.com/a/74787357
  filter:
    runs-on: ubuntu-latest
    name: Filter
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get changed files in the codegen folder
      id: changed
      uses: tj-actions/changed-files@v42
      with:
        files: |
          .github/workflows/build.yml
          codegen/**

    - name: Prevent from running
      if: steps.changed.outputs.any_changed != 'true'
      run: exit 1

  build:
    needs: filter

    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          id: win
        - name: macOS
          os: macos-latest
          id: mac
        - name: Linux
          os: ubuntu-latest
          id: linux

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    env:
      CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # https://github.com/mozilla/sccache/issues/2090
    - name: Download custom sccache
      uses: robinraju/release-downloader@v1.9
      with:
        repository: cgytrus/sccache
        latest: true
        fileName: 'sccache-*-x86_64-apple-darwin.zip'
        tarBall: false
        zipBall: false
        out-file-path: "epic-sccache"
      if: matrix.config.id == 'mac'

    - name: Setup custom sccache
      run: |
        7z x "epic-sccache/sccache-*-x86_64-apple-darwin.zip" -o"epic-sccache"
        echo "$GITHUB_WORKSPACE/epic-sccache" >> $GITHUB_PATH
        chmod +x "epic-sccache/sccache"
      if: matrix.config.id == 'mac'

    # https://github.com/hendrikmuhs/ccache-action/pull/182
    - name: Setup sccache
      uses: chirag-droid/ccache-action@main
      with:
        variant: sccache
        key: ${{ matrix.config.id }}-v1

    - name: Setup CPM Cache
      uses: actions/cache@v4
      with:
        path: cpm-cache
        key: cpm-${{ matrix.config.id }}-v1-${{ hashFiles('codegen/CMakeLists.txt') }}
        restore-keys: |
          cpm-${{ matrix.config.id }}-v1-

    - name: Install Ninja
      shell: bash
      run: |
        curl -L https://github.com/ninja-build/ninja/releases/latest/download/ninja-${{ matrix.config.id }}.zip -o ninja.zip
        7z x ninja.zip -o"$GITHUB_WORKSPACE/ninja"
        echo "$GITHUB_WORKSPACE/ninja" >> $GITHUB_PATH

    - name: Configure
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -G Ninja

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: geode-codegen-${{ matrix.config.id }}
        path: |
          ./build/Codegen
          ./build/Codegen.exe
        if-no-files-found: ignore

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/prebuilt-codegen'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4

    - name: Update Codegen Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: codegen
        name: 'Codegen Release'
        prerelease: false
        body: Geode codegen release for commit ${{ github.sha }}.
        files: |
          ./geode-codegen-win.exe
          ./geode-codegen-mac
          ./geode-codegen-linux
